export const buildSettings = ({ uid, color, minNumberDays, url, couponSupport }) => ({
  widgetMode: {
    uid,
    lang: 'ru',
    currency: 'RUB',
    type: 'horizontal',
    width: '100%',
    background: '#ffffff',
    bg_alpha: '100',
    padding: '24',
    border_radius: '8',
    font_type: 'arial',
    font_size: '18',
    without_title: 'on',
    title_color: '#222222',
    title_size: '18',
    inp_color: '#999999',
    inp_bordhover: '#999999',
    inp_bordcolor: '#CCCCCC',
    inp_alpha: '100',
    btn_background: `#${color}`,
    btn_background_over: `#${color}`,
    btn_textcolor: '#fff',
    btn_textover: '#fff',
    btn_bordcolor: `#${color}`,
    btn_bordhover: `#${color}`,
    text_concierge: 'Получи скидку через Bnovo Concierge',
    dates_preset: 'on',
    dfrom_today: 'on',
    dto_value: minNumberDays,
    url,
    promo: couponSupport ? 'on' : '',
  },

  bookingMode: {
    uid,
    html_id: 'booking_iframe',
    lang: 'ru',
    width: 'auto',
    height: 'auto',
    rooms: '',
    IsMobile: '0',
    fixed_header_selector: '.header',
    fixed_mobile_header_selector: '.header',
    fixed_mobile_header_width: 991,
  },
});
